//
//  HomeWorker.swift
//  CleanSwiftV1
//
//  Created by Chayawat Suntornrak on 27/11/2562 BE.
//  Copyright (c) 2562 Chayawat Suntornrak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
  func doSomeWork() {
  }
}
